
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";


export const GET_ORDER_START = "GET_ORDER_START";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAIL = "GET_ORDER_FAIL";

export const GET_PRODUCT_START = "GET_PRODUCT_START";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";

export const GET_STAT_START = "GET_STAT_START";
export const GET_STAT_SUCCESS = "GET_STAT_SUCCESS";
export const GET_STAT_FAIL = "GET_STAT_FAIL";


export const GET_CHART_START = "GET_CHART_START"
export const GET_CHART_SUCCESS = "GET_CHART_SUCCESS"
export const GET_CHART_FAIL = "GET_CHART_FAIL"